name: C/C++ CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Clone Repository
      uses: actions/checkout@v3

    - name: Install Dependencies
      run:  |
        sudo apt-get update
        sudo apt-get install -y valgrind

    - name: Autoconfigure Build
      run: make autoconfig

    - name: Test
      run: make test release
